FibonacciSeries/Fibonacci.java
FibonacciSeries/README.md
eightpuzzles/AStar.java
eightpuzzles/Algo.java
eightpuzzles/BFS.java
eightpuzzles/DFS.java
eightpuzzles/MainTestClass.java
eightpuzzles/README.md
eightpuzzles/SolutionEngine.java
eightpuzzles/State.java
eightpuzzles/Status.java

Solution engine for 8 puzzles with DFS, BFS and AStar (incomplete)

8 Puzzles game solution with DFS, BFS and Astar

---

math/euclids_gcd/java/Euclid.java

Add Euclid's GCD java implementation

---

search/linear_search.cpp

very basic linear search with minor error handling.
I know it's extremely basic stuff but having no search algos directory made me mad! :D
C++ implementation!
Have a good day! 👍

Added the 1st search algo! (linear search)

---

dynamic programming/edit_distance.cpp
dynamic programming/edit_distance_space_efficient.cpp

@felipecustodio , please review this.

edit distance solutions added

---

FibonacciSeries/racket/fibonacci.rkt
FibonacciSeries/racket/fibonacci.rkt~

Added basic Fibonacci sequence functions (the same functions as the Java implementation) implemented in Racket.

added racket fibonacci sequence functions

---

sorting/postman_sort/postmansort.cc

This sorting type is comparable to the bucket sort, but it does use the hierarchical structure of elements

Adding Postman sort

---

NeuralNetwork/XOR/Network.java
NeuralNetwork/XOR/XorTest.java

Others to follow - from beginners NN to DL

XOR Test NeuralNetwork - Simple - Others to follow

---

blockchain/python/Blockchain.py

A very simple blockchain in python with simple mining to create and verify each blocks in blockchain

Simple blockchain with simple mining similar to bitcoin

---

data_structures/Stack/C/StackDS.c

insert, delete and display operation performed on Stack Data Structure

Operations related to stack added,in C Language

---

search/binary_search/BinarySearch.java

I added a generic java implementation of the binary search algorithm, which supports search from a list (List<T), and search from an array.

Add generic Java implementation of binary search algorithm

---

sorting/Merge_sort/MergeSort.java
sorting/Merge_sort/README.md

I added a Java implementation for the merge sort algorithm, as well as a small README.

Add README and generic java implementation for merge sort algorithm

---

dynamic programming/longest-arithmetic-progression.cpp

Added longest-arithmetic-progression in c++

---

Greedy Algorithms/Job_Sequencing.cpp

Added Greedy Algorithm Folder and an Algorithm in it

---

math/average_score/c++/averageScore.cpp

C++ Calculate average of three valid score input from user

calculate average

---

math/is_prime/c#/is_prime.cs

Add is_prime csharp (C#) version #66

Add is_prime csharpt

---

math/fibonacci/Scala/fibonacci.scala

Added Scala version of Fibonacci in math/fibonacci, using a recursive approach.
#66

Scala version in math/fibonacci

---

math/fraction/fraction.cpp

C++ program multiply fractions

add fraction

---

Greedy Algorithms/activity_selection.cpp

#hacktoberfest 
Added Activity Selection to Greedy Algorithm

added to Greedy Algorithm

---

network/mail_sender.py

Python script to send emails to a list of contacts. (#66)

Mail sender script

---

sorting/Insertion_sort/insertions_sort.js

add insertion sort using javascript

---

search/linear_search/linear_search.py

Hi,
I have added linear search implementation in python which is illustrated by an example as well.
Thanks and Regards
Vaibhav

Added linear_search.py

---

data_structures/linked_list_stack_queue/LinkedList.c

Implementation of Linked List in C.
For Hacktoberfest 2019(#126)

Implement Linked List in C

---

math/is_prime/python/is_prime.py

Python implementation to check if number is prime.
Ref: Hacktoberfest 2019 #126

Added Python example for is_prime

---

sorting/radix_sort/cpp/RadixSort.cpp

Radix sort in cpp

---

sorting/counting_sort/CountingSort.cpp
sorting/radix_sort/cpp/RadixSort.cpp

Counting Sort on cpp

---

sorting/shell_sort/csharp/ShellSort.cs

This is a C# implementation of Shell Sort algorithm.
Refer: Hacktoberfest 2019 issue https://github.com/pirataspinhal/algorithms/issues/126

Add shell sort implementation in csharp

---

greedy_algorithms/KnapSack.cpp
greedy_algorithms/MakingChangeProblem.cpp

Added Knapsack Problem and Making a Change Problem! 

---

math/fibonacci/C++/effecientfib.cpp

To increase efficiency of calculation we should store the already calculated fibonacci numbers in an array so that we do not have to calculate them again and again during recursion.This makes the process much faster.

Faster method to calculate fibonacci numbers

---

sorting/Bubble_sort/bubble.kt

Added kotlin implementation of bubblesort

Added kotlin implementation of bubblesort

---

math/armstrong_number/Python/armstrong_no.py
sorting/quick_sort/c/quick_sort.c

Added code for armstrong number in python as part of hacktober as my previous pr went invalid because it looked like my code was picked up from a repl link but it was my repl account I myself had written that code

added code for armstrong number in python 

---

sorting/Merge_sort/mergesort.js

Merge Sort in JavaScript

---

data_structures/lists/Cpp/list.cpp
data_structures/lists/Cpp/list.h
data_structures/lists/Cpp/main.cpp
data_structures/lists/Cpp/node.cpp
data_structures/lists/Cpp/node.h

data structures
I put up an implementation of a linked list. Hopefully others can use the classes I wrote as a starting point to write their own algorithms.
---
:beers: Hacktoberfest (#66)

Adding cpp linked list classes

---

sorting/TimSort.java

fun sorting algorithm implemented
sorting algorithm
learning algorithm, etc... Feel free to classify your code as you see fit.)
implemented timsort in java
faster and more easily.
---
:beers: Hacktoberfest (#66)

Created TimSort

---

Euclidean_Algorithm.c

Hey! I added Euclidean Algorithm.

Euclidean Algorithm

---

ImageSharpening.py

Given image, the code sharpens it and saves the intermediate images in the same folder.
Please include a small description of your algorithm/data structure and add a reference to the Hacktoberfest issue (#66)

Given image, sharpens it by enhancing edges

---

System Programing/lefFactoring.cpp

System Programming/lefFactoring Program added
